Repository bavix/laravel-wallet, pull requests merged in 2024-02, with the labels that each got.

#877 [11.x] received transfers
  src/Interfaces/Wallet.php
  src/Models/Wallet.php
  src/Traits/HasWallet.php
  tests/Units/Service/AtomicServiceTest.php
Labels: enhancement, 11.x-dev

#878 [10.x] received transfers
  src/Models/Wallet.php
  tests/Units/Service/AtomicServiceTest.php
Labels: enhancement, 10.x-dev

#879 [11.x] raise the minimum version of laravel to 11
  composer.json
  database/2023_12_30_113122_extra_columns_removed.php
  phpstan.common.neon
  phpstan.src.baseline.neon
  phpstan.tests.baseline.neon
  phpunit.xml
  tests/Infra/TestCase.php
  tests/Units/Domain/TransactionsFilterTest.php
  tests/Units/Domain/WalletTest.php
Labels: technical debt, 11.x-dev

#882 [11.x] revert collation
  .github/workflows/phpunits.yaml
  tests/Infra/TestCase.php
Labels: technical debt, 11.x-dev

#884 [11.x] testSetNameAttribute
  tests/Units/Domain/BalanceTest.php
Labels: php, technical debt

#889 [11.x] method casts()
  src/Models/Transaction.php
  src/Models/Transfer.php
  src/Models/Wallet.php
Labels: 11.x-dev

#891 [11.x] returned driftingly/rector-laravel
  composer.json
  rector.php
  tests/Infra/Models/ItemMultiPrice.php
Labels: technical debt, github_actions, 11.x-dev
