Repository bavix/laravel-wallet, pull requests merged in 2024-01, with the labels that each got.

#844 add docs bavix/laravel-wallet-uuid
  docs/_sidebar.md
  docs/laravel-wallet-uuid.md
Labels: docs

#859 add a check for passing the correct model
  tests/Units/Domain/DiscountTest.php
Labels: 9.x-dev, 10.x-dev, 11.x-dev

#858 Update Transfer Model
  src/Models/Transfer.php
Labels: 9.x-dev, 10.x-dev, 11.x-dev

#865 [11.x] Adding an Extra column to the transfer table
  database/2024_01_24_185401_add_extra_column_in_transfer.php
  phpstan.src.baseline.neon
  src/External/Contracts/ExtraDtoInterface.php
  src/External/Dto/Extra.php
  src/Internal/Assembler/TransferDtoAssembler.php
  src/Internal/Assembler/TransferDtoAssemblerInterface.php
  src/Internal/Assembler/TransferLazyDtoAssembler.php
  src/Internal/Assembler/TransferLazyDtoAssemblerInterface.php
  src/Internal/Dto/BasketDto.php
  src/Internal/Dto/BasketDtoInterface.php
  src/Internal/Dto/TransferDto.php
  src/Internal/Dto/TransferDtoInterface.php
  src/Internal/Dto/TransferLazyDto.php
  src/Internal/Dto/TransferLazyDtoInterface.php
  src/Internal/Repository/TransferRepository.php
  src/Internal/Transform/TransferDtoTransformer.php
  src/Internal/Transform/TransferDtoTransformerInterface.php
  src/Models/Transfer.php
  src/Objects/Cart.php
  src/Services/PrepareService.php
  src/Services/TransferService.php
  src/Traits/CanExchange.php
  src/Traits/HasGift.php
  tests/Units/Api/TransferHandlerTest.php
  tests/Units/Domain/BasketTest.php
  tests/Units/Domain/CartTest.php
  tests/Units/Domain/ExtraTest.php
Labels: enhancement, requires testing, internal api, 11.x-dev

#866 [11.x] Add interfaces for High performance api handles
  deptrac.yaml
  src/External/Api/TransactionQuery.php
  src/External/Api/TransactionQueryHandler.php
  src/External/Api/TransactionQueryHandlerInterface.php
  src/External/Api/TransactionQueryInterface.php
  src/External/Api/TransferQuery.php
  src/External/Api/TransferQueryHandler.php
  src/External/Api/TransferQueryHandlerInterface.php
  src/External/Api/TransferQueryInterface.php
Labels: 11.x-dev

#870 [11.x] Added *FloatQuery for High performance api handles
  deptrac.yaml
  src/External/Api/TransactionFloatQuery.php
  src/External/Api/TransferFloatQuery.php
  tests/Units/Api/TransactionHandlerTest.php
  tests/Units/Api/TransferHandlerTest.php
Labels: enhancement, 11.x-dev
